import { default as React } from 'react';
import { AffineTransform } from './affine_transform';
import { DataStatistics } from './data_statistics';
import { HistogramLabelProps } from './histogram_default_label';
export declare const HistogramGraphWidth: React.Context<number>;
export declare const HistogramGraphHeight: React.Context<number>;
export declare const HistogramPlotWidth: React.Context<number>;
export declare const HistogramPlotHeight: React.Context<number>;
export declare const HistogramRange: React.Context<(number | null)[]>;
export declare const HistogramDomain: React.Context<(number | null)[]>;
export declare const HistogramRangeStatistics: React.Context<DataStatistics>;
export declare const HistogramDomainStatistics: React.Context<DataStatistics>;
export declare const HistogramYAxisGuideLines: React.Context<number[]>;
export declare const HistogramGraphValueIndex: React.Context<number>;
export declare const HistogramGraphValue: React.Context<number | null>;
export declare const HistogramGraphValueRect: React.Context<{
    x: number;
    y: number;
    width: number;
    height: number;
}>;
export declare const HistogramLabelsBBox: React.Context<DOMRect | null>;
export declare const HistogramRangeAffineTransform: React.Context<AffineTransform>;
export declare const HistogramDomainAffineTransform: React.Context<AffineTransform>;
export declare const HistogramYAxisLabelComponent: React.Context<HistogramLabel>;
export type HistogramLabel = React.FC<HistogramLabelProps>;
