import { Channel } from '../../../../../../../../../../../../src/async/channel';
import { Sink } from '../../../../../../../../../../../../src/async/sink/sink';
import { default as WebSocketStatus } from '../../../../../../../../../../../../src/models/web_worker/web_socket/status/web_socket_status';
import { WebWorkerProxyRequest } from '../../../../../../../../../../../../src/models/web_worker/web_worker_proxy_request';
import { WebWorkerProxyResponse } from '../../../../../../../../../../../../src/models/web_worker/web_worker_proxy_response';
import { default as CappuccinoNodeValidatorResponse } from '../responses/node_validator_response';
import { WebWorkerNodeValidatorAPI } from '../web_worker_proxy_api';
export default class FakeDataCappuccinoNodeValidatorAPI implements WebWorkerNodeValidatorAPI {
    readonly responseStream: Channel<WebWorkerProxyResponse>;
    readonly requestStream: Channel<WebWorkerProxyRequest>;
    readonly lifecycleResponseSink: Sink<WebSocketStatus>;
    readonly nodeValidatorResponseSink: Sink<CappuccinoNodeValidatorResponse>;
    constructor(requestStream: Channel<WebWorkerProxyRequest>, responseStream: Channel<WebWorkerProxyResponse>);
    get stream(): AsyncIterable<WebWorkerProxyResponse>;
    send(request: WebWorkerProxyRequest): Promise<void>;
    private prng;
    private latestBlock;
    private latestBlocks;
    private latestVoters;
    private histogramBlockTimeData;
    private histogramBlockSizeData;
    private histogramBlockTransactionData;
    private generateVotersFromBlockDetail;
    private histogramBlockHeightData;
    private updateBlockDetails;
    initializeState(): Promise<void>;
    startProcessing(): Promise<void>;
    handleRequests(): Promise<void>;
    streamBlocks(): Promise<void>;
    private handleRequest;
    private handleWebSocketCommand;
    private handleNodeValidatorRequest;
    private isConnected;
    private isSubscribedToLatestBlock;
    private isSubscribedToVoters;
    private handleConnect;
    private handleClose;
    private assertIsConnected;
    private handleSubscribeLatestBlock;
    private handleSubscribeNodeIdentity;
    private handleSubscribeVoters;
    private handleRequestBlocksSnapshot;
    private handleRequestHistogramSnapshot;
    private handleRequestNodeIdentitySnapshot;
    private handleRequestVotersSnapshot;
}
