import { AsyncSnapshot } from '../../../../../../../../../../../../src/components/data/async_data/async_snapshot';
import { ESPTokenContract } from '../../../../contracts/esp_token/esp_token_interface';
import { L1Methods } from '../../../../contracts/l1/l1_interface';
import { StakeTableContract } from '../../../../contracts/stake_table/stake_table_interface';
import { default as React } from 'react';
import { Config } from 'wagmi';
import { PerformWriteTransactionState } from './perform_write_states';
export declare const ApproveAsyncIterableContext: React.Context<AsyncIterable<PerformWriteTransactionState> | null>;
export declare const SetApproveAsyncIterableContext: React.Context<React.Dispatch<React.SetStateAction<AsyncIterable<PerformWriteTransactionState> | null>>>;
export declare const ApproveAsyncSnapshotContext: React.Context<AsyncSnapshot<PerformWriteTransactionState>>;
export declare const ProvideApproveAsyncIterableContext: React.FC<React.PropsWithChildren>;
export declare function performApprove(l1Methods: L1Methods<Config, number>, espContract: ESPTokenContract, stakeTableContract: StakeTableContract, setL1Timestamp: React.Dispatch<React.SetStateAction<Date>>): AsyncGenerator<import('./perform_write_states').PerformWriteTransactionWaiting | import('./perform_write_states').PerformWriteTransactionSucceeded | import('./perform_write_states').PerformWriteTransactionReceiptWaiting | import('./perform_write_states').PerformWriteTransactionReceiptRetrieved, void, unknown>;
