export declare function isString(a: unknown): a is string;
export declare function isNumber(a: unknown): a is number;
export declare function isBoolean(a: unknown): a is boolean;
export declare function isObject(a: unknown): a is object | null;
export declare function isNotNull<T>(a: T | null): a is T;
export declare function isNotUndefined<T>(a: T | undefined): a is T;
export declare function isUnknown(a: unknown): a is unknown;
export declare const inflateString: (a: unknown) => string;
export declare const inflateNumber: (a: unknown) => number;
export declare const inflateBoolean: (a: unknown) => boolean;
export declare const inflateObject: (a: unknown) => object | null;
export declare const inflateUnknown: (a: unknown) => unknown;
export declare function inflateBigInt(a: unknown): bigint;
type reviverFunc = (key: string, value: unknown) => unknown;
export declare function reviveWithReviverFunc(revivers: Record<string, reviverFunc>, key: string, value: unknown): unknown;
export declare function isArrayFunc<T>(checker: (a: unknown) => a is T): (a: unknown) => a is T[];
export declare const isNumberArray: (a: unknown) => a is number[];
export declare const isUnknownArray: (a: unknown) => a is unknown[];
export declare const inflateNumberArray: (a: unknown) => number[];
export declare const inflateUnknownArray: (a: unknown) => unknown[];
export declare function inflateTypeOfObjectAndKey<Key extends string, Type>(obj: NonNullable<object | null>, key: Key, inflater: (a: unknown) => Type): Type;
export {};
