import { BlockTag } from 'viem';
import { Config } from 'wagmi';
import { EstimateGasParameters, GetBalanceParameters, GetBlockNumberParameters, GetBlockParameters, GetTransactionParameters, GetTransactionReceiptParameters } from 'wagmi/actions';
import { L1Methods } from './l1_interface';
export declare class L1MethodsRemote<config extends Config, chainId extends config['chains'][number]['id']> implements L1Methods<config, chainId> {
    private readonly config;
    private readonly chainID;
    constructor(config: Config, chainID: chainId);
    getBalance(parameters: GetBalanceParameters<config>): Promise<import('@wagmi/core').GetBalanceReturnType>;
    estimateGas(parameters: EstimateGasParameters<config, chainId>): Promise<bigint>;
    getTransactionReceipt(parameters: GetTransactionReceiptParameters<config>): Promise<{
        blobGasPrice?: bigint | undefined;
        blobGasUsed?: bigint | undefined;
        blockHash: import('viem').Hash;
        blockNumber: bigint;
        contractAddress: import('abitype').Address | null | undefined;
        cumulativeGasUsed: bigint;
        effectiveGasPrice: bigint;
        from: import('abitype').Address;
        gasUsed: bigint;
        logs: import('viem').Log<bigint, number, false>[];
        logsBloom: import('viem').Hex;
        root?: `0x${string}` | undefined;
        status: "success" | "reverted";
        to: import('abitype').Address | null;
        transactionHash: import('viem').Hash;
        transactionIndex: number;
        type: import('viem').TransactionType;
        chainId: number;
    }>;
    getTransaction(parameters: GetTransactionParameters<config, chainId>): Promise<{
        type: "legacy";
        value: bigint;
        input: import('viem').Hex;
        s: import('viem').Hex;
        from: import('abitype').Address;
        r: import('viem').Hex;
        to: import('abitype').Address | null;
        nonce: number;
        hash: import('viem').Hash;
        v: bigint;
        gas: bigint;
        blobVersionedHashes?: undefined | undefined;
        gasPrice: bigint;
        maxFeePerBlobGas?: undefined | undefined;
        maxFeePerGas?: undefined | undefined;
        maxPriorityFeePerGas?: undefined | undefined;
        accessList?: undefined | undefined;
        authorizationList?: undefined | undefined;
        chainId: number;
        yParity?: undefined | undefined;
        typeHex: import('viem').Hex | null;
        blockNumber: bigint;
        blockHash: `0x${string}`;
        transactionIndex: number;
    } | {
        type: "eip2930";
        value: bigint;
        input: import('viem').Hex;
        s: import('viem').Hex;
        from: import('abitype').Address;
        r: import('viem').Hex;
        to: import('abitype').Address | null;
        nonce: number;
        hash: import('viem').Hash;
        v: bigint;
        gas: bigint;
        blobVersionedHashes?: undefined | undefined;
        gasPrice: bigint;
        maxFeePerBlobGas?: undefined | undefined;
        maxFeePerGas?: undefined | undefined;
        maxPriorityFeePerGas?: undefined | undefined;
        accessList: import('viem').AccessList;
        authorizationList?: undefined | undefined;
        chainId: number;
        yParity: number;
        typeHex: import('viem').Hex | null;
        blockNumber: bigint;
        blockHash: `0x${string}`;
        transactionIndex: number;
    } | {
        type: "eip1559";
        value: bigint;
        input: import('viem').Hex;
        s: import('viem').Hex;
        from: import('abitype').Address;
        r: import('viem').Hex;
        to: import('abitype').Address | null;
        nonce: number;
        hash: import('viem').Hash;
        v: bigint;
        gas: bigint;
        blobVersionedHashes?: undefined | undefined;
        gasPrice?: undefined | undefined;
        maxFeePerBlobGas?: undefined | undefined;
        maxFeePerGas: bigint;
        maxPriorityFeePerGas: bigint;
        accessList: import('viem').AccessList;
        authorizationList?: undefined | undefined;
        chainId: number;
        yParity: number;
        typeHex: import('viem').Hex | null;
        blockNumber: bigint;
        blockHash: `0x${string}`;
        transactionIndex: number;
    } | {
        type: "eip4844";
        value: bigint;
        input: import('viem').Hex;
        s: import('viem').Hex;
        from: import('abitype').Address;
        r: import('viem').Hex;
        to: import('abitype').Address | null;
        nonce: number;
        hash: import('viem').Hash;
        v: bigint;
        gas: bigint;
        blobVersionedHashes: readonly import('viem').Hex[];
        gasPrice?: undefined | undefined;
        maxFeePerBlobGas: bigint;
        maxFeePerGas: bigint;
        maxPriorityFeePerGas: bigint;
        accessList: import('viem').AccessList;
        authorizationList?: undefined | undefined;
        chainId: number;
        yParity: number;
        typeHex: import('viem').Hex | null;
        blockNumber: bigint;
        blockHash: `0x${string}`;
        transactionIndex: number;
    } | {
        type: "eip7702";
        value: bigint;
        input: import('viem').Hex;
        s: import('viem').Hex;
        from: import('abitype').Address;
        r: import('viem').Hex;
        to: import('abitype').Address | null;
        nonce: number;
        hash: import('viem').Hash;
        v: bigint;
        gas: bigint;
        blobVersionedHashes?: undefined | undefined;
        gasPrice?: undefined | undefined;
        maxFeePerBlobGas?: undefined | undefined;
        maxFeePerGas: bigint;
        maxPriorityFeePerGas: bigint;
        accessList: import('viem').AccessList;
        authorizationList: import('viem').SignedAuthorizationList;
        chainId: number;
        yParity: number;
        typeHex: import('viem').Hex | null;
        blockNumber: bigint;
        blockHash: `0x${string}`;
        transactionIndex: number;
    }>;
    getBlock<includeTransactions extends boolean = false, blockTag extends BlockTag = 'latest'>(parameters?: GetBlockParameters<includeTransactions, blockTag, config, chainId>): Promise<{
        number: blockTag extends "pending" ? null : bigint;
        nonce: blockTag extends "pending" ? null : `0x${string}`;
        size: bigint;
        hash: blockTag extends "pending" ? null : `0x${string}`;
        timestamp: bigint;
        blobGasUsed: bigint;
        gasUsed: bigint;
        logsBloom: blockTag extends "pending" ? null : `0x${string}`;
        baseFeePerGas: bigint | null;
        difficulty: bigint;
        excessBlobGas: bigint;
        extraData: import('viem').Hex;
        gasLimit: bigint;
        miner: import('abitype').Address;
        mixHash: import('viem').Hash;
        parentBeaconBlockRoot?: `0x${string}` | undefined;
        parentHash: import('viem').Hash;
        receiptsRoot: import('viem').Hex;
        sealFields: import('viem').Hex[];
        sha3Uncles: import('viem').Hash;
        stateRoot: import('viem').Hash;
        totalDifficulty: bigint | null;
        transactionsRoot: import('viem').Hash;
        uncles: import('viem').Hash[];
        withdrawals?: import('viem').Withdrawal[] | undefined | undefined;
        withdrawalsRoot?: `0x${string}` | undefined;
        transactions: includeTransactions extends true ? ({
            type: "legacy";
            value: bigint;
            input: import('viem').Hex;
            s: import('viem').Hex;
            from: import('abitype').Address;
            r: import('viem').Hex;
            to: import('abitype').Address | null;
            nonce: number;
            hash: import('viem').Hash;
            v: bigint;
            gas: bigint;
            blobVersionedHashes?: undefined | undefined;
            gasPrice: bigint;
            maxFeePerBlobGas?: undefined | undefined;
            maxFeePerGas?: undefined | undefined;
            maxPriorityFeePerGas?: undefined | undefined;
            accessList?: undefined | undefined;
            authorizationList?: undefined | undefined;
            chainId?: number | undefined;
            yParity?: undefined | undefined;
            typeHex: import('viem').Hex | null;
            blockNumber: (blockTag extends "pending" ? true : false) extends infer T ? T extends (blockTag extends "pending" ? true : false) ? T extends true ? null : bigint : never : never;
            blockHash: (blockTag extends "pending" ? true : false) extends infer T_1 ? T_1 extends (blockTag extends "pending" ? true : false) ? T_1 extends true ? null : `0x${string}` : never : never;
            transactionIndex: (blockTag extends "pending" ? true : false) extends infer T_2 ? T_2 extends (blockTag extends "pending" ? true : false) ? T_2 extends true ? null : number : never : never;
        } | {
            type: "eip2930";
            value: bigint;
            input: import('viem').Hex;
            s: import('viem').Hex;
            from: import('abitype').Address;
            r: import('viem').Hex;
            to: import('abitype').Address | null;
            nonce: number;
            hash: import('viem').Hash;
            v: bigint;
            gas: bigint;
            blobVersionedHashes?: undefined | undefined;
            gasPrice: bigint;
            maxFeePerBlobGas?: undefined | undefined;
            maxFeePerGas?: undefined | undefined;
            maxPriorityFeePerGas?: undefined | undefined;
            accessList: import('viem').AccessList;
            authorizationList?: undefined | undefined;
            chainId: number;
            yParity: number;
            typeHex: import('viem').Hex | null;
            blockNumber: (blockTag extends "pending" ? true : false) extends infer T_3 ? T_3 extends (blockTag extends "pending" ? true : false) ? T_3 extends true ? null : bigint : never : never;
            blockHash: (blockTag extends "pending" ? true : false) extends infer T_4 ? T_4 extends (blockTag extends "pending" ? true : false) ? T_4 extends true ? null : `0x${string}` : never : never;
            transactionIndex: (blockTag extends "pending" ? true : false) extends infer T_5 ? T_5 extends (blockTag extends "pending" ? true : false) ? T_5 extends true ? null : number : never : never;
        } | {
            type: "eip1559";
            value: bigint;
            input: import('viem').Hex;
            s: import('viem').Hex;
            from: import('abitype').Address;
            r: import('viem').Hex;
            to: import('abitype').Address | null;
            nonce: number;
            hash: import('viem').Hash;
            v: bigint;
            gas: bigint;
            blobVersionedHashes?: undefined | undefined;
            gasPrice?: undefined | undefined;
            maxFeePerBlobGas?: undefined | undefined;
            maxFeePerGas: bigint;
            maxPriorityFeePerGas: bigint;
            accessList: import('viem').AccessList;
            authorizationList?: undefined | undefined;
            chainId: number;
            yParity: number;
            typeHex: import('viem').Hex | null;
            blockNumber: (blockTag extends "pending" ? true : false) extends infer T_6 ? T_6 extends (blockTag extends "pending" ? true : false) ? T_6 extends true ? null : bigint : never : never;
            blockHash: (blockTag extends "pending" ? true : false) extends infer T_7 ? T_7 extends (blockTag extends "pending" ? true : false) ? T_7 extends true ? null : `0x${string}` : never : never;
            transactionIndex: (blockTag extends "pending" ? true : false) extends infer T_8 ? T_8 extends (blockTag extends "pending" ? true : false) ? T_8 extends true ? null : number : never : never;
        } | {
            type: "eip4844";
            value: bigint;
            input: import('viem').Hex;
            s: import('viem').Hex;
            from: import('abitype').Address;
            r: import('viem').Hex;
            to: import('abitype').Address | null;
            nonce: number;
            hash: import('viem').Hash;
            v: bigint;
            gas: bigint;
            blobVersionedHashes: readonly import('viem').Hex[];
            gasPrice?: undefined | undefined;
            maxFeePerBlobGas: bigint;
            maxFeePerGas: bigint;
            maxPriorityFeePerGas: bigint;
            accessList: import('viem').AccessList;
            authorizationList?: undefined | undefined;
            chainId: number;
            yParity: number;
            typeHex: import('viem').Hex | null;
            blockNumber: (blockTag extends "pending" ? true : false) extends infer T_9 ? T_9 extends (blockTag extends "pending" ? true : false) ? T_9 extends true ? null : bigint : never : never;
            blockHash: (blockTag extends "pending" ? true : false) extends infer T_10 ? T_10 extends (blockTag extends "pending" ? true : false) ? T_10 extends true ? null : `0x${string}` : never : never;
            transactionIndex: (blockTag extends "pending" ? true : false) extends infer T_11 ? T_11 extends (blockTag extends "pending" ? true : false) ? T_11 extends true ? null : number : never : never;
        } | {
            type: "eip7702";
            value: bigint;
            input: import('viem').Hex;
            s: import('viem').Hex;
            from: import('abitype').Address;
            r: import('viem').Hex;
            to: import('abitype').Address | null;
            nonce: number;
            hash: import('viem').Hash;
            v: bigint;
            gas: bigint;
            blobVersionedHashes?: undefined | undefined;
            gasPrice?: undefined | undefined;
            maxFeePerBlobGas?: undefined | undefined;
            maxFeePerGas: bigint;
            maxPriorityFeePerGas: bigint;
            accessList: import('viem').AccessList;
            authorizationList: import('viem').SignedAuthorizationList;
            chainId: number;
            yParity: number;
            typeHex: import('viem').Hex | null;
            blockNumber: (blockTag extends "pending" ? true : false) extends infer T_12 ? T_12 extends (blockTag extends "pending" ? true : false) ? T_12 extends true ? null : bigint : never : never;
            blockHash: (blockTag extends "pending" ? true : false) extends infer T_13 ? T_13 extends (blockTag extends "pending" ? true : false) ? T_13 extends true ? null : `0x${string}` : never : never;
            transactionIndex: (blockTag extends "pending" ? true : false) extends infer T_14 ? T_14 extends (blockTag extends "pending" ? true : false) ? T_14 extends true ? null : number : never : never;
        })[] : `0x${string}`[];
        chainId: number;
    }>;
    getBlockNumber(parameters?: GetBlockNumberParameters<config, chainId>): Promise<bigint>;
}
