name: Build

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04-8core
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"

      - name: Cache Turbo
        uses: actions/cache@v6
        with:
          path: .turbo/cache
          key: turbo-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            turbo-${{ runner.os }}-

      - name: Install Dependencies
        run: npm ci --workspaces

      - name: Build All Packages
        run: npx turbo build

      - name: Lint All Packages
        run: npx turbo lint

      - name: Test All Packages
        run: npx turbo test

      - name: Coverage All Packages
        run: npx turbo coverage

      - name: Components Coverage Main Branch
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: "Espresso Block Explorer Components"
          working-directory: "./packages/espresso-block-explorer-components/"
          file-coverage-mode: all

      - name: Components Coverage Pull Request
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: "Espresso Block Explorer Components"
          working-directory: "./packages/espresso-block-explorer-components/"
          file-coverage-mode: changes

      - name: Generate Storybook Static Files for Espresso Block Explorer Components
        run: |
          npm --workspace=packages/espresso-block-explorer-components run build-storybook

      - name: Deploy Espresso Block Explorer Components Storybook
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/espresso-block-explorer-components/storybook-static
